### ISSUE TITLE
s3 upload fails for large files

### ISSUE THREAD

**Issue by grahame** [muccg/bpa-ingest#1]
```
Traceback (most recent call last):
  File "/home/ubuntu/venv.bpa-ingest/bin/bpa-ingest", line 9, in <module>
    load_entry_point('bpaingest==1.0.0', 'console_scripts', 'bpa-ingest')()
  File "/home/ubuntu/bpa-ingest/bpaingest/cli.py", line 98, in main
    args.func(ckan, args)
  File "/home/ubuntu/bpa-ingest/bpaingest/cli.py", line 41, in wheat_pathogens
    ingest_wheat_pathogens(ckan, args.path, args.upload)
  File "/home/ubuntu/bpa-ingest/bpaingest/wheat_pathogens/ingest.py", line 133, in ingest
    ckan_sync_data(ckan, organism, group_obj, samples, files, do_upload)
  File "/home/ubuntu/bpa-ingest/bpaingest/wheat_pathogens/ingest.py", line 115, in ckan_sync_data
    sync_files(ckan, packages, files, do_upload)
  File "/home/ubuntu/bpa-ingest/bpaingest/wheat_pathogens/ingest.py", line 91, in sync_files
    create_resource(ckan, ckan_obj, do_upload)
  File "/home/ubuntu/bpa-ingest/bpaingest/ops.py", line 85, in create_resource
    ckan.action.resource_create(upload=read_back, **ckan_obj)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/ckanapi/common.py", line 50, in action
    files=files)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/ckanapi/remoteckan.py", line 82, in call_action
    status, response = self._request_fn(url, data, headers, files, requests_kwargs)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/ckanapi/remoteckan.py", line 86, in _request_fn
    r = requests.post(url, data=data, headers=headers, files=files, **requests_kwargs)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/requests/models.py", line 298, in prepare
    self.prepare_body(data, files, json)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/requests/models.py", line 449, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/home/ubuntu/venv.bpa-ingest/local/lib/python2.7/site-packages/requests/models.py", line 152, in _encode_files
    fdata = fp.read()
MemoryError

```

**Comment by aahunter** [comment]
Looks to me like ckanapi is not using requests to do a streaming upload. Hence requests is trying to load the file into memory and failing.

**Comment by grahame** [comment]
Yes, hopefully I have fixed it :-) I had to hack ckanapi, I'll clean that patch up for merge if it proves good. Trying it now.

**Comment by grahame** [comment]
Fixed, pending upstreaming of the ckanapi changes.
